services:
  backend:
    image: ghcr.io/m4tx/shrt-backend:master
    restart: unless-stopped
    volumes:
      - shrt_data:/app/data
      - ./config/prod.toml:/app/config/prod.toml:ro

  frontend:
    image: ghcr.io/m4tx/shrt-frontend:master
    restart: unless-stopped

  proxy:
    image: ghcr.io/m4tx/shrt-proxy:master
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
    ports:
      - 8000:80

volumes:
  shrt_data:
