//! Generated by cot CLI 0.5.0 on 2026-02-04 17:52:44+00:00

#[derive(Debug, Copy, Clone)]
pub(super) struct Migration;
impl ::cot::db::migrations::Migration for Migration {
    const APP_NAME: &'static str = "shrt-backend";
    const DEPENDENCIES: &'static [::cot::db::migrations::MigrationDependency] = &[];
    const MIGRATION_NAME: &'static str = "m_0001_initial";
    const OPERATIONS: &'static [::cot::db::migrations::Operation] =
        &[::cot::db::migrations::Operation::create_model()
            .table_name(::cot::db::Identifier::new("shrt_backend__link"))
            .fields(&[
                ::cot::db::migrations::Field::new(
                    ::cot::db::Identifier::new("id"),
                    <cot::db::Auto<i32> as ::cot::db::DatabaseField>::TYPE,
                )
                .auto()
                .primary_key()
                .set_null(<cot::db::Auto<i32> as ::cot::db::DatabaseField>::NULLABLE),
                ::cot::db::migrations::Field::new(
                    ::cot::db::Identifier::new("slug"),
                    <String as ::cot::db::DatabaseField>::TYPE,
                )
                .set_null(<String as ::cot::db::DatabaseField>::NULLABLE),
                ::cot::db::migrations::Field::new(
                    ::cot::db::Identifier::new("url"),
                    <String as ::cot::db::DatabaseField>::TYPE,
                )
                .set_null(<String as ::cot::db::DatabaseField>::NULLABLE),
                ::cot::db::migrations::Field::new(
                    ::cot::db::Identifier::new("created_at"),
                    <chrono::DateTime<chrono::Utc> as ::cot::db::DatabaseField>::TYPE,
                )
                .set_null(<chrono::DateTime<chrono::Utc> as ::cot::db::DatabaseField>::NULLABLE),
                ::cot::db::migrations::Field::new(
                    ::cot::db::Identifier::new("visits"),
                    <i32 as ::cot::db::DatabaseField>::TYPE,
                )
                .set_null(<i32 as ::cot::db::DatabaseField>::NULLABLE),
            ])
            .build()];
}

#[derive(::core::fmt::Debug)]
#[::cot::db::model(model_type = "migration")]
struct _Link {
    #[model(primary_key)]
    pub id: cot::db::Auto<i32>,
    pub slug: String,
    pub url: String,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub visits: i32,
}
